In [1]:
data_path = '/share/data/imagenet-pytorch'

import os
os.chdir('/engram/nklab/hossein/recurrent_models/BLT_models/')
!pwd

#--wandb_p 'vggface2' --wandb_r 'blt_bl' 

/engram/nklab/hossein/recurrent_models/BLT_models


In [ ]:
!python main.py --distributed 1 --save_model 0 --pool 'max' --dataset 'imagenet' --num_layers 6 --model 'blt_blt' --epochs 100 --lr .1 --loss_choice 'weighted' --loss_gamma 0 --recurrent_steps 10 --lr_drop 10 --port '12379' --run 'm' --batch_size 128


| distributed init (rank 0): env://
| distributed init (rank 1): env://
| distributed init (rank 2): env://
cuda
Number of model parameters: 7310632
blt(
  (conv_input): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
  (maxpool_input): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (output_prenorm_0): Identity()
  (non_lin_0): ReLU(inplace=True)
  (norm_0): GroupNorm(32, 64, eps=1e-05, affine=True)
  (output_0): Identity()
  (conv_0_0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_0_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (output_prenorm_1): Identity()
  (non_lin_1): ReLU(inplace=True)
  (norm_1): GroupNorm(32, 64, eps=1e-05, affine=True)
  (output_1): Identity()
  (conv_1_0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_1_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_1_2): Sequential(
    (blurpool): BlurPool(
      (

In [ ]:
works:

!python main.py --distributed 1 --save_model 0 --pool 'blur' --dataset 'imagenet' --num_layers 6 --model 'blt_blt' --epochs 100 --lr .0005 --loss_choice 'weighted' --loss_gamma 0 --recurrent_steps 10 --lr_drop 100 --port '12379' --run 'm' --batch_size 128

# 40.

In [3]:
!python main.py --distributed 0 --save_model 1 --pool 'blur' --dataset 'imagenet_vggface2' --num_layers 6 --model 'blt_bl' --epochs 100 --lr .0005 --loss_choice 'weighted' --loss_gamma 0 --recurrent_steps 10 --lr_drop 100 --port '12379' --run 'maxpool' --batch_size 16 --port '12370'


cuda
100%|█████████████████████████████████████| 1920/1920 [00:00<00:00, 1945.50it/s]
Number of model parameters: 6305844
blt(
  (conv_input): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
  (maxpool_input): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (non_lin_0): ReLU(inplace=True)
  (norm_0): GroupNorm(32, 64, eps=1e-05, affine=True)
  (output_0): Identity()
  (conv_0_0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_0_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (non_lin_1): ReLU(inplace=True)
  (norm_1): GroupNorm(32, 64, eps=1e-05, affine=True)
  (output_1): Identity()
  (conv_1_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_1_2): Sequential(
    (blurpool): BlurPool(
      (pad): ReflectionPad2d((1, 2, 1, 2))
    )
    (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (non_lin_2): ReLU(inplace=True)
  (norm_2): Gr

In [2]:
# --wandb_p 'vggface2' --wandb_r 'bl_6_run5' 
!python main.py --distributed 1 --save_model 1 --dataset 'imagenet_vggface2' --num_layers 6 --model 'blt_b_top2linear' --epochs 100 --lr .0005 --loss_choice 'weighted' --loss_gamma 0.2 --recurrent_steps 10 --batch_size 32

/engram/nklab/hossein/recurrent_models/BLT_models/models/blt.py:230: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if conn_input is not 0:
| distributed init (rank 0): env://
| distributed init (rank 1): env://
cuda
100%|█████████████████████████████████████| 3890/3890 [00:02<00:00, 1577.15it/s]
56 28 2
28 14 2
14 7 2
7 1 7
1 1 1
Number of model parameters: 12473650
blt(
  (conv_input): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
  (maxpool_input): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (non_lin_0): ReLU(inplace=True)
  (norm_0): GroupNorm(32, 64, eps=1e-05, affine=True)
  (output_0): Identity()
  (conv_0_1): Sequential(
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (non_lin_1): ReLU(inplace=True)
  (norm_1): GroupNorm(32, 128, eps=1e-05, affine=True)
  (output_1): Identity()
  (conv_1_

In [ ]:
!python main.py --save_model 0 --dataset 'imagenet' --wandb_p 'imagenet' --wandb_r 'blt_bl'  --model 'blt_bl' --epochs 100 --lr .001

In [7]:
import torch
a = torch.zeros(3,3)
print(a is not 0)

_top2linear
--epochs 100 --lr .0005 --loss_choice 'weighted' --loss_gamma 0 --recurrent_steps 10 --lr_drop 100 --port '12370' --run 35 --batch_size 128

True


<>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/tmp/ipykernel_71418/692844870.py:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  print(a is not 0)


Imagent

In [12]:
#!/usr/bin/env python

import subprocess
import os
import numpy as np
import time

script = f'''#!/bin/sh
#
#
#SBATCH --account=nklab
#SBATCH --job-name=blnd  # The job name.
#SBATCH --gres=gpu:4

#SBATCH --cpus-per-task=20

ml load anaconda3-2023.07

cd /engram/nklab/hossein/recurrent_models/BLT_models/

conda activate diff

python main.py --distributed 1 --save_model 0 --dataset 'imagenet' --num_layers 6 --model 'blt_bl' --wandb_p 'imagenet' --wandb_r 'blt_bl' --epochs 100 --lr .0005 --loss_choice 'weighted' --loss_gamma 0 --recurrent_steps 10 --lr_drop 100 --port '12390' --run 'blt_bl_nodrop' --pool 'max' --batch_size 32

'''

bash_script_path = "/engram/nklab/hossein/batch_scripts/imagenet_nb.sh"
os.chdir('/engram/nklab/hossein/batch_scripts/')

with open(bash_script_path, "w+") as bash_script_file:
    bash_script_file.write(script)

subprocess.run(['sbatch', '/engram/nklab/hossein/batch_scripts/imagenet_nb.sh'
])

Submitted batch job 3996127


CompletedProcess(args=['sbatch', '/engram/nklab/hossein/batch_scripts/imagenet_nb.sh'], returncode=0)

In [ ]:
python main.py --save_model 1 --dataset 'vggface2' --wandb_p 'vggface2' --wandb_r 'b_small_0.0005'  --model 'blt_b' --num_layers 6 --epochs 100 --lr .0005 --lr_drop 10 --port '12391' --run 22


VGGFace2

In [6]:
#!/usr/bin/env python

import subprocess
import os
import numpy as np
import time

script = f'''#!/bin/sh
#
#
#SBATCH --account=nklab
#SBATCH --job-name=blt_vgg  # The job name.
#SBATCH --gres=gpu:3
#SBATCH --nodelist=ax26
#SBATCH --cpus-per-task=18

ml load anaconda3-2019.03

cd /engram/nklab/hossein/recurrent_models/BLT_models/

conda activate py39

python main.py --distributed 1 --save_model 1 --dataset 'vggface2' --wandb_p 'vggface2' --wandb_r 'bl_blur_img_g' --num_layers 6 --model 'blt_bl' --epochs 100 --lr .0005 --loss_choice 'weighted' --loss_gamma 0 --recurrent_steps 10 --lr_drop 100 --port '12381' --run 'blur_norm_img_g' --pool 'blur' --batch_size 128

'''

bash_script_path = "/engram/nklab/hossein/batch_scripts/imagenet_nb.sh"
os.chdir('/engram/nklab/hossein/batch_scripts/')

with open(bash_script_path, "w+") as bash_script_file:
    bash_script_file.write(script)

subprocess.run(['sbatch', '/engram/nklab/hossein/batch_scripts/imagenet_nb.sh'
])

Submitted batch job 3730795


CompletedProcess(args=['sbatch', '/engram/nklab/hossein/batch_scripts/imagenet_nb.sh'], returncode=0)

In [2]:
import torch
torch.cuda.device_count()

2

In [3]:
x = torch.tensor([1., 2., 3.])
x.to('cuda:0')

tensor([1., 2., 3.], device='cuda:0')

In [4]:
x.to('cuda:1')

tensor([1., 2., 3.], device='cuda:1')

In [5]:
import torch
torch.cuda.device_count()

2

In [6]:
a = torch.randn(size=(2, 4), device='cuda:0')

In [7]:
a

tensor([[-0.1245,  1.1608, -0.1005, -1.2000],
        [ 0.9481, -0.5120, -0.6132, -0.4649]], device='cuda:0')

In [8]:
a.to('cuda:1')

tensor([[-0.1245,  1.1608, -0.1005, -1.2000],
        [ 0.9481, -0.5120, -0.6132, -0.4649]], device='cuda:1')